services:
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - '8080:80'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data: